create table email_verifications (
    email_verification_fail_count INT DEFAULT 0 not null,
    email_verification_expiry timestamp(6),
    email_verification_requested_at timestamp(6),
    email_verification_tries INT NOT NULL DEFAULT 0,
    email_verification_token varchar(8),
    id bigint generated by default as identity,
    email varchar(320) not null unique,
    primary key (id)
);


ALTER TABLE email_verifications
ALTER COLUMN email_verification_expiry TYPE TIMESTAMP WITH TIME ZONE
USING email_verification_expiry AT TIME ZONE 'UTC';

ALTER TABLE users
ALTER COLUMN email_verification_requested_at TYPE TIMESTAMP WITH TIME ZONE
USING email_verification_requested_at AT TIME ZONE 'UTC';