
    create table diagnosis_results (
        id integer generated by default as identity,
        name varchar(512),
        body_part varchar(255) check (body_part in ('EYE','MOUTH')),
        description TEXT,
        pet_species varchar(255) not null check (pet_species in ('DOG','CAT')),
        primary key (id)
    );

    create table diagnosis_status (
        id smallint generated by default as identity,
        description varchar(128),
        name varchar(128) not null unique,
        primary key (id)
    );

    create table language (
        id integer generated by default as identity,
        code varchar(10) unique,
        name varchar(128),
        primary key (id)
    );

    create table notification_template_type (
        id integer generated by default as identity,
        color_code varchar(7),
        name varchar(512) not null unique,
        description varchar(2048),
        primary key (id)
    );

    create table permissions (
        id integer generated by default as identity,
        description varchar(1024),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table pets (
        birthday date,
        is_neutered boolean,
        weight smallint,
        created_at timestamp(6) not null,
        id bigint generated by default as identity,
        mbti varchar(8),
        owner_id bigint not null,
        updated_at timestamp(6) not null,
        breed varchar(255),
        gender varchar(255) check (gender in ('MALE','FEMALE','UNKNOWN')),
        profile_image TEXT,
        species varchar(255) check (species in ('DOG','CAT')),
        primary key (id)
    );

    create table refresh_tokens (
        expires_at timestamp(6) not null,
        user_id bigint not null,
        id uuid not null,
        primary key (id)
    );

    create table role_permissions (
        permission_id integer not null,
        role_id smallint not null,
        primary key (permission_id, role_id)
    );

    create table roles (
        id smallint generated by default as identity,
        description varchar(1024),
        name varchar(255) not null unique,
        primary key (id)
    );

    create table shelters (
        latitude numeric(10,8),
        longitude numeric(11,8),
        id bigint generated by default as identity,
        phone_number varchar(20) unique,
        address varchar(512),
        introduction TEXT,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table social_login_provider (
        id smallint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table user_account_actions (
        action_by_user_id bigint,
        action_timestamp timestamp(6) not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        action_type varchar(50) not null check (action_type in ('DEACTIVATED','REACTIVATED','BANNED','UNBANNED','DELETED','RESTORED','EMAIL_VERIFIED','PASSWORD_CHANGED')),
        reason varchar(2048),
        primary key (id)
    );

    create table users (
        email_verification_fail_count smallint,
        login_attempt SMALLINT DEFAULT 0 not null,
        password_reset_token_verify_fail_count smallint,
        role_id smallint not null,
        created_at timestamp(6) not null,
        email_verification_expiry timestamp(6),
        email_verification_requested_at timestamp(6),
        email_verification_token varchar(8),
        id bigint generated by default as identity,
        login_attempt_started_at timestamp(6),
        password_reset_requested_at timestamp(6),
        password_reset_token_expiry timestamp(6),
        updated_at timestamp(6) not null,
        nickname varchar(128) not null,
        email varchar(256) not null unique,
        password varchar(255),
        password_reset_token varchar(255),
        profile_pic TEXT,
        primary key (id)
    );

    alter table if exists pets 
       add constraint FKoygstexeo9ivoylgrdrv2tc39 
       foreign key (owner_id) 
       references users;

    alter table if exists refresh_tokens 
       add constraint FK1lih5y2npsf8u5o3vhdb9y0os 
       foreign key (user_id) 
       references users;

    alter table if exists role_permissions 
       add constraint FKegdk29eiy7mdtefy5c7eirr6e 
       foreign key (permission_id) 
       references permissions;

    alter table if exists role_permissions 
       add constraint FKn5fotdgk8d1xvo8nav9uv3muc 
       foreign key (role_id) 
       references roles;

    alter table if exists user_account_actions 
       add constraint FKg97gvgg6wdbntaoomexsts2y1 
       foreign key (action_by_user_id) 
       references users;

    alter table if exists user_account_actions 
       add constraint FKsp91sxhdibd4v445t23kyuum 
       foreign key (user_id) 
       references users;

    alter table if exists users 
       add constraint FKp56c1712k691lhsyewcssf40f 
       foreign key (role_id) 
       references roles;
