--
-- 1. Conditions Table (Lookup Table for all possible diseases/models)
--
CREATE TABLE conditions (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255) NOT NULL, -- e.g., 'Cataract', 'Glaucoma'
    species VARCHAR(4) NOT NULL CHECK (species IN ('DOG', 'CAT')), -- Used to filter which conditions apply
    description TEXT,

    -- Optional: Add a unique constraint for condition name and pet type if the name might be the same
    -- but apply to different pet types (e.g., 'Retinal Atrophy' for both)
    UNIQUE (name, species),
    primary key (id)
);

CREATE TABLE submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    -- New Foreign Key: Links this submission directly to a specific pet
    pet_id BIGINT NOT NULL REFERENCES pets(id),
    photo_url TEXT NOT NULL,
    submitted_at timestamp(6) not null, 
    completed_at timestamp(6) not null
);

CREATE TABLE diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    submission_id BIGINT NOT NULL REFERENCES submissions(id),
    condition_id INT NOT NULL REFERENCES conditions(id),
    
    probability NUMERIC(5, 4) NOT NULL CHECK (probability >= 0 AND probability <= 1),
    model_md5_hash VARCHAR(32) NOT NULL, -- Store the MD5 hash of the model used for inference
    
    UNIQUE (submission_id, condition_id)
);