-- V24__create_localization_tables.sql

----------------------------------------------------------
-- 1. Languages Table Enhancement
-- Adds a 'native_name' column to the existing 'languages' table
-- to better support localization.
----------------------------------------------------------
DROP TABLE IF EXISTS language;

CREATE TABLE languages (
    id integer generated by default as identity,
    name VARCHAR(255) NOT NULL, -- English name (e.g., 'Korean')
    native_name VARCHAR(255) NOT NULL, -- Native name (e.g., '한국어')
    code VARCHAR(128) NOT NULL, -- ISO code (e.g., 'ko')
    CONSTRAINT uq_languages_code UNIQUE (code),
    CONSTRAINT uq_languages_name UNIQUE (name),
    primary key (id)
);

-- Insert the base language (Korean) since your data is currently in Korean.
-- We can add English later in the translation data.
INSERT INTO languages (code, name, native_name) VALUES
('ko', 'Korean', '한국어')
ON CONFLICT (code) DO NOTHING;

INSERT INTO languages (name, native_name, code) VALUES
('English', 'English', 'en')
ON CONFLICT (code) DO NOTHING;
---

----------------------------------------------------------
-- 2. Condition Translations Table
-- Stores the translated names and descriptions for 'conditions'.
----------------------------------------------------------
CREATE TABLE condition_translations (
    condition_id INT NOT NULL,
    language_id INT NOT NULL,
    translated_name VARCHAR(255) NOT NULL,
    translated_description TEXT NOT NULL,

    PRIMARY KEY (condition_id, language_id),

    -- Foreign key to the core conditions table
    CONSTRAINT fk_ct_condition
        FOREIGN KEY (condition_id)
        REFERENCES conditions (id) ON DELETE RESTRICT,

    -- Foreign key to the languages table
    CONSTRAINT fk_ct_language
        FOREIGN KEY (language_id)
        REFERENCES languages (id) ON DELETE CASCADE
);
---

----------------------------------------------------------
-- 3. Check Method Translations Table (For 'Eye Examination', 'Urine Analysis', etc.)
-- Stores the translated descriptions for 'check_methods'.
----------------------------------------------------------
CREATE TABLE check_method_translations (
    check_method_id INT NOT NULL,
    language_id INT NOT NULL,
    translated_description TEXT NOT NULL,

    PRIMARY KEY (check_method_id, language_id),

    -- Foreign key to the core check_methods table
    CONSTRAINT fk_cmt_check_method
        FOREIGN KEY (check_method_id)
        REFERENCES check_methods (id) ON DELETE CASCADE,

    -- Foreign key to the languages table
    CONSTRAINT fk_cmt_language
        FOREIGN KEY (language_id)
        REFERENCES languages (id) ON DELETE CASCADE
);