-- SOCIAL_ACCOUNT_USER 권한
INSERT INTO role_permissions (role_id, permission_id)
SELECT R.id, P.id
FROM roles R
CROSS JOIN permissions P
WHERE R.name = 'SOCIAL_ACCOUNT_USER' AND P.name IN (
    -- 일반 사용자 권한 (General User Permissions)
    'can_deactivate_account',
    'can_reactivate_account',
    'can_view_own_profile',
    'can_edit_own_profile',
    'can_view_other_user_profile',
    'can_follow_user',
    'can_unfollow_user',
    'can_block_user',
    'can_add_pet',
    'can_view_own_pets',
    'can_view_own_pet_detail',
    'can_edit_pet',
    'can_delete_pet',
    'can_start_walk',
    'can_end_walk',
    'can_update_walk_record',
    'can_view_own_walk_records',
    'can_view_own_walk_detail',
    'can_delete_walk_record',
    'can_view_weekly_summary',
    'can_use_health_check',
    'can_view_own_health_records'
);

CREATE TABLE social_login_user (
    id bigint generated by default as identity,

    -- User 엔티티와의 연관 관계 (ManyToOne)
    user_id BIGINT NOT NULL,

    -- SocialLoginProvider 엔티티와의 연관 관계 (ManyToOne)
    provider_id SMALLINT NOT NULL,

    -- 소셜 제공자에서 부여한 사용자 고유 ID (unique = true)
    provider_user_id VARCHAR(255) NOT NULL UNIQUE,

    -- 소셜 로그인 시 받은 추가 데이터 (JSON 등)
    extra_data TEXT,

    -- 타임스탬프

    created_at timestamp(6) not null,
    updated_at timestamp(6) not null,

    primary key (id),
    -- 외래 키 제약 조건 설정
    -- user 테이블은 프로젝트에 따라 이름이 다를 수 있으나, 여기서는 'app_user' 또는 'user'로 가정합니다.
    -- 필요에 따라 아래 'user' 테이블명을 실제 사용자 테이블명으로 수정해야 합니다.
    
    CONSTRAINT fk_social_user_user_id
        FOREIGN KEY (user_id)
        REFERENCES users (id) ON DELETE CASCADE, -- 사용자 탈퇴 시 연결 정보도 삭제

    CONSTRAINT fk_social_user_provider_id
        FOREIGN KEY (provider_id)
        REFERENCES social_login_provider (id) ON DELETE RESTRICT
);

-- 3. Unique Constraints (고유 제약 조건) 설정
-- @UniqueConstraint(columnNames = {"provider_id", "provider_user_id"})
-- 동일 제공자 내에서 ID는 한 번만 등록 가능
CREATE UNIQUE INDEX uix_provider_user ON social_login_user (provider_id, provider_user_id);

-- @UniqueConstraint(columnNames = {"user_id", "provider_id"})
-- 한 사용자는 각 제공자별로 한 번씩만 연결 가능
CREATE UNIQUE INDEX uix_user_provider ON social_login_user (user_id, provider_id);