-- Table for UrineAnalyte
CREATE TABLE urine_analytes (
    id integer generated by default as identity,
    name VARCHAR(512) NOT NULL UNIQUE,
    description VARCHAR(2048),

    PRIMARY KEY (id)
);

-- REFERENCE_COLOR_TABLE: Dict[str, Dict[str, Tuple[int, int, int]]] = {
--     "Leukocytes": {
--         "Neg.": (168, 165, 140),
--         "Trace 15": (158, 150, 141),
--         "Small 70": (159, 143, 139),
--         "Moderate 125": (152, 123, 145),
--         "Large 500": (128, 95, 137),
--     },
--     "Nitrite": {
--         "Neg.": (169, 166, 161),
--         "Positive": (175, 152, 158),
--     },
--     "Urobilinogen": {
--         "Normal": (175, 166, 152),
--         "16": (173, 135, 124),
--         "Trace 32": (169, 97, 93),
--         "64+": (171, 86, 79),
--         "128+": (169, 70, 65),
--     },
--     "Protein": {
--         "Neg.": (164, 159, 94),
--         "Trace": (147, 157, 97),
--         "0.3": (137, 154, 109),
--         "1.0": (113, 151, 130),
--         "3.0": (122, 155, 154),
--         "20.0": (101, 149, 137),
--     },
--     "pH": {
--         "5.0": (172, 136, 43),
--         "6.0": (144, 130, 25),
--         "6.5": (120, 126, 29),
--         "7.0": (101, 109, 34),
--         "7.5": (79, 105, 34),
--         "8.0": (56, 94, 33),
--         "8.5": (1, 108, 139),
--     },
--     "Blood": {
--         "Neg.": (176, 132, 72),
--         "Non hemolyzed 10": (167, 130, 66),
--         "Hemolyzed 10": (161, 125, 28),
--         "25 Small": (136, 121, 34),
--         "80 Moderate": (82, 112, 43),
--         "200 Large": (20, 79, 31),
--     },
--     "Specific Gravity": {
--         "1.000": (2, 107, 106),
--         "1.005": (62, 96, 65),
--         "1.010": (88, 106, 49),
--         "1.015": (130, 122, 49),
--         "1.020": (150, 134, 49),
--         "1.025": (167, 138, 38),
--         "1.030": (175, 144, 47),
--     },
--     "Ketone": {
--         "Neg.": (180, 137, 120),
--         "Trace 0.5": (173, 116, 103),
--         "Small 1.5": (169, 87, 97),
--         "Moderate 4.0": (160, 35, 66),
--         "8.0": (114, 16, 50),
--         "Large 16": (85, 12, 48),
--     },
--     "Bilirubin": {
--         "Neg.": (179, 175, 169),
--         "Small 17": (172, 153, 129),
--         "Moderate 50": (175, 155, 140),
--         "Large 100": (178, 146, 134),
--     },
--     "Glucose": {
--         "Neg.": (125, 155, 152),
--         "Trace 5": (109, 149, 105),
--         "15": (106, 122, 33),
--         "30": (132, 105, 20),
--         "60": (125, 67, 31),
--         "110": (101, 42, 24),
--     },
-- }

INSERT into urine_analytes (name, description) values
    ('Leukocytes', '배뇨 내 백혈구 존재 여부'),
    ('Nitrite', '배뇨 내 아질산염 존재 여부'),
    ('Urobilinogen', '요로빌리노겐 수치'),
    ('Protein', '요단백 농도'),
    ('pH', '요의 산도 또는 알칼리도'),
    ('Blood', '요 내 혈액 존재 여부'),
    ('Specific Gravity', '요 내 용질 농도'),
    ('Ketone', '요 내 케톤체 존재 여부'),
    ('Bilirubin', '요 내 빌리루빈 수치'),
    ('Glucose', '요 내 포도당 농도');

-- Table for UrineMeasurement
CREATE TABLE urine_measurements (
    id BIGINT generated by default as identity,
    submission_id UUID NOT NULL,
    analyte_id INTEGER NOT NULL,
    value VARCHAR(512) NOT NULL,
    color_r SMALLINT DEFAULT 0,
    color_g SMALLINT DEFAULT 0,
    color_b SMALLINT DEFAULT 0,
    CONSTRAINT fk_submission FOREIGN KEY (submission_id) REFERENCES submissions(id) ON DELETE SET NULL,
    CONSTRAINT fk_analyte FOREIGN KEY (analyte_id) REFERENCES urine_analytes(id),
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX idx_unique_submission_analyte
    ON urine_measurements (submission_id, analyte_id);
