ALTER TABLE pets
ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE
USING created_at AT TIME ZONE 'UTC';

ALTER TABLE pets
ALTER COLUMN updated_at TYPE TIMESTAMP WITH TIME ZONE
USING updated_at AT TIME ZONE 'UTC';

ALTER TABLE refresh_tokens
ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE
USING expires_at AT TIME ZONE 'UTC';

ALTER TABLE user_account_actions
ALTER COLUMN action_timestamp TYPE TIMESTAMP WITH TIME ZONE
USING action_timestamp AT TIME ZONE 'UTC';